/*
 * Seguridad por filas por centro, tanda 2: el flujo clínico de eventos (ADR 0008, incremento G1). Eventos clínicos y su contexto,
 * escalados a Medicina, valoraciones de Enfermería y de Medicina con sus versiones y correcciones, rectificaciones, seguimientos y sus
 * acciones, indicaciones, protocolos urgentes, informes de derivación, intentos de llamada y comunicaciones a la familia. Amplía la
 * política de 0030 con el mismo predicado y las mismas reglas.
 */

ALTER SECURITY POLICY seg.pol_centro
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.eventos_clinicos,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.eventos_clinicos AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.eventos_clinicos AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.eventos_contexto,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.eventos_contexto AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.eventos_contexto AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.escalados_medicina,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.escalados_medicina AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.escalados_medicina AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria_versiones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria_versiones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria_versiones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria_correcciones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria_correcciones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_enfermeria_correcciones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas_versiones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas_versiones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas_versiones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas_correcciones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas_correcciones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_medicas_correcciones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_rectificaciones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_rectificaciones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.valoraciones_rectificaciones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimientos,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimientos AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimientos AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimiento_acciones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimiento_acciones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimiento_acciones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimientos_medicos,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimientos_medicos AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimientos_medicos AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimiento_medico_acciones,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimiento_medico_acciones AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.seguimiento_medico_acciones AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.indicaciones_medicas,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.indicaciones_medicas AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.indicaciones_medicas AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.protocolos_urgentes,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.protocolos_urgentes AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.protocolos_urgentes AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.protocolo_urgente_registros,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.protocolo_urgente_registros AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.protocolo_urgente_registros AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.informes_derivacion,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.informes_derivacion AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.informes_derivacion AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.intentos_llamada_familia,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.intentos_llamada_familia AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.intentos_llamada_familia AFTER UPDATE,
    ADD FILTER PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.comunicaciones_familiares,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.comunicaciones_familiares AFTER INSERT,
    ADD BLOCK PREDICATE seg.fn_centro_del_ambito(centro_id) ON dbo.comunicaciones_familiares AFTER UPDATE;
GO
